### ISSUE TITLE
Website does not load

### ISSUE THREAD

**Issue by danieldegroot2** [EdwardBetts/owl-map#12]
Website loads indefinitely at https://map.osm.wikidata.link/ .

Browser: Any
OS: Windows 10

**Comment by EdwardBetts** [comment]
The server had crashed, I talked to the hosting centre and got them to reboot it. It is working now. I'll add some monitoring.

**Comment by danieldegroot2** [comment]
@EdwardBetts I think it's down again.

**Comment by EdwardBetts** [comment]
I restarted the web server, it is back.

**Comment by danieldegroot2** [comment]
Returns 502 Bad Gateway error now.

**Comment by EdwardBetts** [comment]
It is very unhappy, database queries are taking a long time. I'm debugging.

**Comment by danieldegroot2** [comment]
It seems to be working again.
