### ISSUE TITLE
Use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by danieldegroot2** [EdwardBetts/owl-map#14]
I would like to suggest using the now preferred https://tile.openstreetmap.org URL instead of the [current one](https://github.com/search?q=user%3AEdwardBetts%20.tile.openstreetmap.org&type=code), see

https://github.com/openstreetmap/operations/issues/737

**Comment by EdwardBetts** [comment]
Good point. Fixed in commit eaca7a9
